### ISSUE TITLE
Installation includes dev directory

### ISSUE THREAD

**Issue by awvwgk** [qcscine/chemoton#2] opened 2022-08-13 20:32 UTC
Running pip install will incorrectly include the `dev` directory

```
  running install_egg_info
  Copying scine_chemoton.egg-info to build/bdist.linux-x86_64/wheel/scine_chemoton-2.1.0-py3.10.egg-info
  running install_scripts
  adding license file "LICENSE.txt" (matched pattern "LICEN[CS]E*")
  creating build/bdist.linux-x86_64/wheel/scine_chemoton-2.1.0.dist-info/WHEEL
  creating '/tmp/pip-wheel-twm84qyb/scine_chemoton-2.1.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'dev/__init__.py'
  adding 'dev/conan/__init__.py'
  adding 'dev/conan/base.py'
  adding 'dev/conan/utils.py'
```

**Comment by steinmig** [comment] 2022-08-15 09:53
I can't reproduce this, both installing from sources and from pypi does not give me the dev directory in the installed package.

Does 
```diff
     python_requires=">={}".format(".".join(str(n) for n in min_version)),
-    packages=find_packages(exclude=["docs", "tests"]),
+    packages=find_packages(exclude=["docs", "tests", "dev"]),
     entry_points={
```
in setup.py resolve your issue?

**Comment by awvwgk** [comment] 2022-08-15 10:40
Not initializing the submodules also seems to work.

**Comment by steinmig** [comment] 2022-08-15 17:53
Yes, not having the files present certainly prevents them from being copied^^

I thought that you meant `dev` was installed within the chemoton package, but now noticed that we indeed unknowingly also install a python package called `dev` due to our conan code being in the submodule. This should now fix your issue and will be included in the next release

```diff
      python_requires=">={}".format(".".join(str(n) for n in min_version)),
-     packages=find_packages(exclude=["docs", "tests"]),
+     packages=find_packages(include=["scine_chemoton", "scine_chemoton.*"],
+                            exclude=["scine_chemoton.tests*"]),
      entry_points={
```

**Comment by weymutht** [comment] 2023-05-12 07:33
This is fixed with release 3.0.0.

**Closed as completed by weymutht** 2023-05-12 07:33 UTC
Labels: Staged
